[[projects]]
project_id = "rpi-example-1"
name = "Example raspberry pi project"

[projects.bitbake]
revision = { tag = "1.50.3" }
git_url = "https://github.com/openembedded/bitbake.git"

[projects.openembedded_core]
revision = { branch = "hardknott" }
git_url = "https://github.com/openembedded/openembedded-core.git"

[[projects.layers]]
submodule_name = "meta-openembedded"
relative_path = "meta-python"
git_url = "https://github.com/openembedded/meta-openembedded.git"
revision = { branch = "hardknott" }

[[projects.layers]]
submodule_name = "meta-openembedded"
relative_path = "meta-networking"
git_url = "https://github.com/openembedded/meta-openembedded.git"
revision = { branch = "hardknott" }

[[projects.layers]]
submodule_name = "meta-raspberrypi"
git_url = "git://git.yoctoproject.org/meta-raspberrypi"
revision = { branch = "hardknott" }

[[projects.layers]]
name = "meta-helloworld"
