[package]
name = "yoctoctl"
version = "0.1.0"
authors = ["Mathias Myrland <jedimemo@gmail.com>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.4"
git2 = "0.13.22"
itertools = "0.10.1"
serde = { version = "1.0.130", features = ["derive"] }
toml = "0.5.8"
